///////////////////////////////////////////////////////////
//  Course.cs
//  Implementation of the Class Course
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class Course {

		private string dept;
		private int no;
		private string title;

		public Course(){

		}

		~Course(){

		}

	}//end Course

}//end namespace System