///////////////////////////////////////////////////////////
//  DataReader.cs
//  Implementation of the Class DataReader
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Drawing;
using System.Globalization;
using System.Windows.Forms;
using System.Collections.Generic;
using Excel = Microsoft.Office.Interop.Excel;

namespace CourseManager {
	public class DataReader {

        public DataReader()
        {

		}

        public static void ReadTo(SectionsManager manager)
        {
            try
            {
                Excel.Application xApp = new Excel.Application();
                Excel.Workbook xWorkBook = xApp.Workbooks.Open(@"C:\Users\moallem\source\repos\CourseManager\CourseManager\Term Schedule 251.xlsx");
                Excel.Worksheet xWorksheet = xWorkBook.Worksheets[1];

                Excel.Range usedRng = xWorksheet.UsedRange;
                int numberOfRows = usedRng.Rows.Count;



                int row = 2;

                while (row <= numberOfRows)
                {

                    Excel.Range rng = xWorksheet.Cells[row, 1];
                    int term = Convert.ToInt32(rng.Value);

                    rng = xWorksheet.Cells[row, 2];
                    int crn = Convert.ToInt32(rng.Value);

                    rng = xWorksheet.Cells[row, 3];
                    string courseCode = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 4];
                    string dept = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 5];
                    string secNoString = (string)rng.Value;


                    rng = xWorksheet.Cells[row, 6];
                    string title = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 7];
                    string activity = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 8];
                    string daysString = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 9];
                    string startTimeString = (string)rng.Value;

                    object vStart = ((Excel.Range)xWorksheet.Cells[row, 9]).Value2;
                    object vEnd = ((Excel.Range)xWorksheet.Cells[row, 10]).Value2;

                    rng = xWorksheet.Cells[row, 11];
                    string? buildingNo = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 12];
                    string? roomNo = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 13];
                    string? instructor = (string)rng.Value;

                    manager.AddSection(term, crn, courseCode, dept, secNoString, title, activity, daysString, vStart, vEnd, buildingNo, roomNo, instructor);

                    row++;
                }


            }
            catch (Exception ex)
            {
                MessageBox.Show("Error " + ex.StackTrace);
            }
            
            
            
        }

       
    }//end DataReader

}//end namespace System