///////////////////////////////////////////////////////////
//  DataReader.cs
//  Implementation of the Class DataReader
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Drawing;
using System.Globalization;
using System.Windows.Forms;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Excel = Microsoft.Office.Interop.Excel;

namespace CourseManager {
	public class DataReader {

        public DataReader()
        {

		}

        public static void ReadTo(SectionsManager manager)
        {
            Excel.Application? xApp = null;
            Excel.Workbook? xWorkBook = null;
            Excel.Worksheet? xWorksheet = null;
            Excel.Range? usedRng = null;

            try
            {
                xApp = new Excel.Application
                {
                    ScreenUpdating = false,
                    DisplayAlerts = false,
                    Visible = false
                };

                xWorkBook = xApp.Workbooks.Open(@"D:\codes\FullProjects\CourseManager\CourseManager\Term Schedule 251.xlsx", ReadOnly: true);
                xWorksheet = xWorkBook.Worksheets[1];

                usedRng = xWorksheet.UsedRange;
                int numberOfRows = usedRng.Rows.Count;
                object?[,] allValues = (object?[,])usedRng.Value2;

                for (int row = 2; row <= numberOfRows; row++)
                {
                    int term = Convert.ToInt32(allValues[row, 1]);
                    int crn = Convert.ToInt32(allValues[row, 2]);
                    string courseCode = Convert.ToString(allValues[row, 3]) ?? string.Empty;
                    string dept = Convert.ToString(allValues[row, 4]) ?? string.Empty;
                    string secNoString = Convert.ToString(allValues[row, 5]) ?? string.Empty;
                    string title = Convert.ToString(allValues[row, 6]) ?? string.Empty;
                    string activity = Convert.ToString(allValues[row, 7]) ?? string.Empty;
                    string daysString = Convert.ToString(allValues[row, 8]) ?? string.Empty;

                    object? vStart = allValues[row, 9];
                    object? vEnd = allValues[row, 10];

                    string? buildingNo = Convert.ToString(allValues[row, 11]);
                    string? roomNo = Convert.ToString(allValues[row, 12]);
                    string? instructor = Convert.ToString(allValues[row, 13]);

                    manager.AddSection(term, crn, courseCode, dept, secNoString, title, activity, daysString, vStart, vEnd, buildingNo, roomNo, instructor);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error " + ex.StackTrace);
            }
            finally
            {
                xWorkBook?.Close(false);
                xApp?.Quit();

                if (usedRng != null)
                {
                    Marshal.ReleaseComObject(usedRng);
                }

                if (xWorksheet != null)
                {
                    Marshal.ReleaseComObject(xWorksheet);
                }

                if (xWorkBook != null)
                {
                    Marshal.ReleaseComObject(xWorkBook);
                }

                if (xApp != null)
                {
                    Marshal.ReleaseComObject(xApp);
                }
            }
        }

       
    }//end DataReader

}//end namespace System
