///////////////////////////////////////////////////////////
//  DataReader.cs
//  Implementation of the Class DataReader
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Drawing;
using System.Globalization;
using System.Windows.Forms;
using System.Collections.Generic;
using Excel = Microsoft.Office.Interop.Excel;

namespace CourseManager {
	public class DataReader {

        public DataReader(){

		}

        public static Dictionary<int, Section> Read()
        {
            try
            {
                Excel.Application xApp = new Excel.Application();
                Excel.Workbook xWorkBook = xApp.Workbooks.Open(@"C:\Users\s202283440\Source\Repos\CourseManager\CourseManager\Term Schedule 251.xlsx");
                Excel.Worksheet xWorksheet = xWorkBook.Worksheets[1];

                Excel.Range usedRng = xWorksheet.UsedRange;
                int numberOfRows = usedRng.Rows.Count;

                Dictionary<int, Section> sections = new Dictionary<int, Section>();

                int row = 2;

                while (row <= numberOfRows)
                {

                    Excel.Range rng = xWorksheet.Cells[row, 1];
                    int term = (int)rng.Value;

                    rng = xWorksheet.Cells[row, 2];
                    int crn = (int)rng.Value;

                    rng = xWorksheet.Cells[row, 3];
                    string courseCode = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 4];
                    string dept = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 5];
                    string secNoString = (string)rng.Value;
                    bool female = false;
                    if (secNoString.StartsWith("F"))
                    {
                        secNoString = secNoString[1..];
                        female = true;
                    }
                    int secNo = int.Parse(secNoString);

                    rng = xWorksheet.Cells[row, 6];
                    string title = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 7];
                    string activity = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 8];
                    string daysString = (string)rng.Value;

                    rng = xWorksheet.Cells[row, 9];
                    string startTimeString = (string)rng.Value;

                    int startHoure = int.Parse(startTimeString[..2]);
                    int startMinute = int.Parse(startTimeString[3..5]);


                    rng = xWorksheet.Cells[row, 10];
                    string endTimeString = (string)rng.Value;
                    int endHoure = int.Parse(endTimeString[..2]);
                    int endMinute = int.Parse(endTimeString[3..5]);
                    Time time = new Time(daysString, new TimeOnly(startHoure, startMinute), new TimeOnly(endHoure, endMinute));


                    rng = xWorksheet.Cells[row, 11];
                    int buidingNo = (int)rng.Value;

                    rng = xWorksheet.Cells[row, 12];
                    int roomNo = (int)rng.Value;

                    rng = xWorksheet.Cells[row, 13];
                    string instructor = (string)rng.Value;

                    Course course = new Course(dept, courseCode, title);
                    Building building = new Building(buidingNo);
                    Location location = new Location(building, roomNo);
                    Section section = new Section(crn, course, term, activity, female, secNo, location, time, instructor);
                    sections.Add(crn, section);
                    row++;
                }
                return sections;

            }
            catch (Exception ex)
            {
                MessageBox.Show("Error " + ex.StackTrace);
                return new Dictionary<int, Section>();
            }
            
            
        }
	}//end DataReader

}//end namespace System