///////////////////////////////////////////////////////////
//  Location.cs
//  Implementation of the Class Location
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CourseManager {
	public class Location {

		private Building building;
		private string? roomNo;

		public Location(Building building,string? roomNo){
			this.building = building;
			this.roomNo = roomNo;
        }


	}//end Location

}//end namespace System