///////////////////////////////////////////////////////////
//  Section.cs
//  Implementation of the Class Section
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////
namespace CourseManager {
	public class Section {

		private string activity;
		private Course course;
		private int crn;
		private bool female;
		private string? instructor;
		private Location location;
		private int secNo;
		private int term;
		private Time time;
		

		
		public Section(int crn, Course course, int term, string activity, bool female, int secNo, Location location, Time time, string? instructor) {
			this.crn = crn;
			this.course = course;
			this.term = term;
			this.activity = activity;
			this.female = female;
			this.secNo = secNo;
			this.location = location;
			this.time = time;
			this.instructor = instructor;
        }

        internal int GetCrn()
        {
			return crn;
        }
		internal Time GetTime()
		{
			return time;
        }
		public Course GetCourse() {
			return course;
        }
    }//end Section

}//end namespace System