///////////////////////////////////////////////////////////
//  Section.cs
//  Implementation of the Class Section
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using System;
namespace System {
	public class Section {

		private string activity;
		private Course course;
		private int crn;
		private bool gender;
		private string instructor;
		private Location location;
		private int secNo;
		private int term;
		private Time time;
		public System.Course m_Course;
		public System.Location m_Location;
		public System.Time m_Time;

		public Section(){

		}

		~Section(){

		}

	}//end Section

}//end namespace System