///////////////////////////////////////////////////////////
//  Section.cs
//  Implementation of the Class Section
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////
namespace CourseManager {
	public class Section {

		private string activity;
		private Course course;
		private int crn;
		private bool female;
		private string instructor;
		private Location location;
		private int secNo;
		private int term;
		private Time time;
		

		
		public Section(int crn, Course course, int term, string activity, bool female, int secNo, Location location, Time time, string instructor) {
            activity = this.activity;
            course = this.course;
			crn = this.crn;
			female = this.female;
			instructor = this.instructor;
			location = this.location;
			secNo = this.secNo;
			term = this.term;
			time = this.time;
        }

        internal int GetCrn()
        {
			return crn;
        }
		internal Time GetTime()
		{
			return time;
        }
    }//end Section

}//end namespace System