///////////////////////////////////////////////////////////
//  Time.cs
//  Implementation of the Class Time
//  Generated by Enterprise Architect
//  Created on:      23-Oct-2025 9:44:46 PM
//  Original author: s202283440
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace System {
	public class Time {
		//first day is sunday
		private boolen[7] days;//UMTWRFS
		private TimeOnly end;
		private TimeOnly start;

		public Time(){

		}

		~Time(){

		}

	}//end Time

}//end namespace System